### ISSUE TITLE
Request:  Integration with MiningPoolHubStats

### ISSUE THREAD

**Issue by kevharper** [nemosminer/NemosMiner-v2.4.2#218]
I would love for Nemos to integrate with MininingPoolHub stats like has been done with MPM.  
https://github.com/miningpoolhubstats/MultiPoolMiner/releases 

I have switched to MPM for the MPHStats capability but would love to come back to Nemo's if it had the same status reporting capability!

**Comment by 8-cloud** [comment]
Same here. Please :)

**Comment by nemosminer** [comment]
sure i'll get onto that next

**Comment by nemosminer** [comment]
https://miningpoolhubstats.com/

**Comment by kevharper** [comment]
Yes that's the one.  Love the accurate real-time hash rate updates added to the version of MPM by Miningpoolhubstats.

**Comment by nemosminer** [comment]
miningpoolhubstats.com works for my rigs running NemosMiner... i just login at miningpoolhubstats.com added my miningpool API and Ahashpool Zpool BTC wallet address's and all my info came up.....

**Comment by airwalker1** [comment]
Please integrate the reporting files necessary to get the real time information such as hashrate, status, and to view the correct income reporting.

Just adding your BTC address is minimal and the other features are implemented and reported by MPM to the miningpoolhubstats website.

**Comment by kevharper** [comment]
Here is the difference...more accurate stats.

![image](https://user-images.githubusercontent.com/34816613/35477765-f49a2cdc-0398-11e8-9808-a85c795daec4.png)

**Comment by kevharper** [comment]
Here is a good example.   MPM with integrated reporting provides more accurate info.

![image](https://user-images.githubusercontent.com/34816613/35477805-3251c598-039a-11e8-89f0-1a46f4d24b11.png)

**Comment by nemosminer** [comment]
kool i see thanks

**Comment by airwalker1** [comment]
Nemos are you working on this? I was hoping to implement it easily but I'm stuck atm.

**Comment by nemosminer** [comment]
yip but not a priority it will get done

**Comment by nemosminer** [comment]
https://github.com/miningpoolhubstats/NemosMiner-v2.4.2

Big thankyou to: "miningpoolhubstats"

**Comment by nemosminer** [comment]
will be implemented today

**Comment by nemosminer** [comment]
Done

**Comment by kevharper** [comment]
AWESOME!   THANK YOU!

**Comment by airwalker1** [comment]
Reportstatus.ps1 is missing. I added it from MPH but its still got some issues. THANK YOU SO MUCH for this!
