### ISSUE TITLE
issue with miners crashing

### ISSUE THREAD

**Issue by Xeandren** [nemosminer/NemosMiner-v2.4.2#254]
i hope this is the correct place to post this, but i am having issues with the miners crashing on me while i am mining. i am running 3 1080 ti's and 1 980 and on a lot of the algorithms my computer keeps crashing, i have to remove them to allow the miner to run on things like neoscrypt and x17, when it errors i get a message in the miner that says : an illegal memory memory access was encountered, while my friend who runs a 1060 can mine all algorithms with no issues. i tried to back it down to just 2 cards but i still get the same issue. also could SLI enabled be an issue?

**Comment by Xeandren** [comment]
![image](https://user-images.githubusercontent.com/36201679/35870961-01f790a0-0b31-11e8-9160-cb1ae61a836e.png)
 
this is what i see before it crashes.

**Comment by nemosminer** [comment]
i don't support 980...

**Comment by Xeandren** [comment]
well then that would make sense, i apologize i did not see that when i read the instructions, do i need to unplug the card for it to work? i tried mining with just 2 1080's and it still crashed
