### ISSUE TITLE
miner failed: 1

### ISSUE THREAD

**Issue by silimaure777** [nemosminer/NemosMiner-v2.4.2#255]
I tried to start my miner but everytime I tried, i got this message :

Running:
Failed:  1

    Speed Exited   Active   Cnt Command
    ----- ------   ------   --- -------
0,00 PH/s dd:hh:mm 00:00:00 3   VIDIA-TPruvotcuda9\ccminer.exe -a x11evo -o stratum+tcp://x11evo.mine.zpool.ca:3553 -u
                                1FgGJMtDS17NnxxFWcBsXSin1tgcJdYXHo -p GTX1080ti,c=BTC -d 0,1 --api-remote

I can't find a workaround, I'm stuck here, it was working fine on same computer before I updated to 2.4.2. It is working fine on my other computer and I can't find why. The only thing that have change is that I added a GTX 1080ti, I also reinstall nvidia driver just to make sure and SLI is disable.

Help me please.

**Comment by nemosminer** [comment]
zpool has removed x11evo.. 

just your startpoolname.bat and remove x11evo from -Algo list....

**Comment by nemosminer** [comment]
i have changed master already re download and try again..

v2.4.2 https://github.com/nemosminer/NemosMiner-v2.4.2/archive/master.zip

**Comment by silimaure777** [comment]
Thanks I'll give it a try

**Comment by silimaure777** [comment]
Ok so I tried it but I still got same problem with Timetravel, Tribus and Groestl. I had an idea and tried to only use the algo that was using ccminerTpruvotcuda9 and it might be the miner that causing this problem since this version of ccminer doesn't want to start... any other ideas?
