### ISSUE TITLE
Phi Miner issue -> no stratum adresses entered

### ISSUE THREAD

**Issue by guiguijke** [nemosminer/NemosMiner-v2.4.2#256]
Hi There
First, thanks for your awesome tool !
Now my issue, the phi miner stratum adress is not entered.
I've already tried to compare miners files, include.ps1, I've found nothing(but my knowledge is limited)
Others miners are ok
Was working on version 2.4.1
Not working on v2.4.2 anymore
Regards

![phi miner issue 001](https://user-images.githubusercontent.com/36210227/35886168-7289c770-0b90-11e8-8a57-d1704ab8e0c2.png)

![phi miner issue 002](https://user-images.githubusercontent.com/36210227/35886170-74c69590-0b90-11e8-8ecf-f7e7fefceedd.png)

**Comment by nemosminer** [comment]
https://imgur.com/a/AS9r9

phi is offline atm will come back soon not my fault...
