### ISSUE TITLE
difficulty + proxy

### ISSUE THREAD

**Issue by edgemaster69** [nemosminer/NemosMiner-v2.4.2#259]
Helo Nemo,

is it possible to configure algos for difficulty between two values? I am mining on ahashpool and 60% i am mining coins with low profitability (0.00000006) but there are coins with 0.000003. or how to configure it to prefer coins with higher profit?
is it possible to configure proxy for the miner? some of my ports are blocked by provider and he dont want to enable it. :(

thank you

**Comment by edgemaster69** [comment]
or what about to autoswitch algo with port parametr?

**Comment by Nateck** [comment]
As I know, ahashpool is choosing the most profitable coin for mining with selected algo

**Comment by edgemaster69** [comment]
are you sure? today i mined VIVO on altminer. i got 3x more only for VIVO insteed of autoswitch on ahash. (where you can mine VIVO too)

**Comment by jrafaelmdo** [comment]
@edgemaster69 Sorry, but you cannot mine a specific coin in Ahashpool, you can only specify the algo and the pool will automatically pick the most profitable coin at that time and assign you hash power to it.
