### ISSUE TITLE
Zergpool not connecting

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.4.2#268]
It keeps reporting that there is an error when contacting pool and even when starts, after few minutes it loses connection. I'm using version 2.4.2 and it works flawlessly but there this problem with Zergpool. Also there is a problem when reading stats from MPH for profitability. It reports values that are way off compared to sites values.

**Comment by barguin** [comment]
I had the same problem with zerpool. I applied this changed and everything seems to work fine now:
https://github.com/pinpins/Sniffdogminer/compare/4.7...master

**Comment by tr1l3r** [comment]
Ok. Tnx mate. I'll try this out.

**Comment by barguin** [comment]
Well it worked for a while and the problem is back....
Loading pool stats..
Error contacting pool, retrying..

Sorry

**Comment by barguin** [comment]
After more then 12 hours I can say that I had just a few connections errors. So it seems to be doing something.

**Comment by tr1l3r** [comment]
Didn't get the chance to try it out. Will do that tomorrow. Thanx for the update mate. Is the pool paying good btw? Didn't get the chance to test it properly but it seems promising.
