### ISSUE TITLE
an error occurred after the update

### ISSUE THREAD

**Issue by Alex735566** [nemosminer/NemosMiner-v2.4.2#269]
![12-02-2018 080438](https://user-images.githubusercontent.com/35488013/36082628-0749d9f0-0fcd-11e8-8e1e-ad0bcf8d0134.png)

**Comment by tiotoi** [comment]
skol'ko u vas videokart stoit na ferme?

**Comment by Alex735566** [comment]
8

**Comment by nemosminer** [comment]
thanks yeh 2day was a big day for code changes i'll run through some test rigs now may need tidying up...

**Comment by Alex735566** [comment]
напишите как исправите
