### ISSUE TITLE
Miningpoolhub Status Reporting Wrong Info

### ISSUE THREAD

**Issue by kevharper** [nemosminer/NemosMiner-v2.4.2#277]
My GTX970 machine has been mining Equihash for about 20 min but on MPH Stats it is reporting MaxCoin.  The only time it was running MaxCoin was during bench-marking.  

Additionally, while reporting Maxcoin, it appears to be reporting results that don't make sense.

I ended up removing XMRig (launch and crash) and PalginHSR (all kinds of stuff in a Powershell window with high numbers) because they were not behaving.

The worker name is cpuminer but it is a GTX970.

![error](https://user-images.githubusercontent.com/34816613/36239655-647a5d12-11d9-11e8-8a2c-9b0e16df5bf0.JPG)
![capture](https://user-images.githubusercontent.com/34816613/36239682-92404612-11d9-11e8-94a1-1357f2c6f86b.JPG)

**Comment by kevharper** [comment]
Actually I just realized it is not showing the detail info that I got when running MPM  with MPHS  so I am not sure what is going on....

**Comment by nemosminer** [comment]
can you try this one :  https://github.com/miningpoolhubstats/NemosMiner-v2.4.2/archive/master.zip
and report if the same thing is happening please

**Comment by kevharper** [comment]
The issue with the wrong coin showing up in the basic stats went away after a while.  The version you linked to made no difference.  I don't see any of the detailed miner info I saw with MPM and MPHStats.
